#
#               Copyright 2007 Mentor Graphics Corporation
#                         All Rights Reserved.
#
# THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS THE
# PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS SUBJECT
# TO LICENSE TERMS.
#

default: all

all:
	@$(MAKE) -C simpleedit/

clean:
	$(MAKE) clean -C simpleedit/

install:
	$(MAKE) install -C simpleedit/
