/***************************************************************************
*
*               Copyright 2006 Mentor Graphics Corporation
*                         All Rights Reserved.
*
* THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
* THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS
* SUBJECT TO LICENSE TERMS.
*
****************************************************************************/

/***************************************************************************
*
* WARNING: This file is automatically generated. Any changes made to this
*          file may be lost.
*
****************************************************************************/

/*************************************************************************/
/*                                                                       */
/* FILE NAME                                               VERSION       */
/*                                                                       */
/*      ifxui_simpleedit.h                                   2.6.0       */
/*                                                                       */
/* COMPONENT                                                             */
/*                                                                       */
/*      IFXM Integrated Module                                           */
/*                                                                       */
/* DESCRIPTION                                                           */
/*                                                                       */
/*      This file contains the function headers for the integrated       */
/*      module interfacing to the integration layer.                     */
/*                                                                       */
/* DATA STRUCTURES                                                       */
/*                                                                       */
/*      none                                                             */
/*                                                                       */
/* DEPENDENCIES                                                          */
/*                                                                       */
/*      ifxui_module_integration.h          API for modules              */
/*                                                                       */
/*************************************************************************/

#ifndef IFX_IFXUISIMPLEEDIT_MODULE_H
#define IFX_IFXUISIMPLEEDIT_MODULE_H

#include "inflexionui/engine/ifxui_module_integration.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Link enums */

/* Startup / shutdown */

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_Initialize(
        IFX_HMODULEID       hModuleId,
        IFX_HMODULE        *phModule);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ShutDown(
        IFX_HMODULE         hModule);

/* Menus */

/* Field Data */

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldStringSize_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HREQUEST       *phRequest,
        IFX_HELEMENT        hElement,
        const IFX_WCHAR    *szField,
        IFX_INT32          *pSize);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldIntData_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        const IFX_WCHAR    *szField,
        IFX_INT32          *pData);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldFloatData_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        const IFX_WCHAR    *szField,
        float              *pData);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldBoolData_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        const IFX_WCHAR    *szField,
        IFX_BOOL           *pData);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldTimeData_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        const IFX_WCHAR    *szField,
        IFX_TIME           *pData);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldIntData_simpleEditInputMode(
        IFX_HMODULE         hModule,
        IFX_INT32          *pData);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetFieldStringData(
        IFX_HMODULE         hModule,
        IFX_HREQUEST        hRequest,
        IFX_WCHAR          *szData);

/* Element functions */

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_CreateElement_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT       *phElement,
        IFX_HMENUID         hMenuId,
        IFX_HMENU           hMenu,
        IFX_INT32           item,
        const IFX_WCHAR    *body,
        const IFX_WCHAR    *paramStyle,
        IFX_INT32           paramMaxLength,
        const IFX_WCHAR    *paramInputMode,
        IFX_INT32           paramCaretPosition);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_DestroyElement_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ActivateElement_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_DeactivateElement_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ProcessElementKeyUpEvent_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        IFX_INT32           key);

IFX_RETURN_STATUS
    IFXM_ifxuisimpleedit_ProcessElementKeyDownEvent_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        IFX_INT32           key,
        IFX_INT32          *pConsumed);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_GetElementCaretPosition_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement,
        IFX_INT32          *pIndex);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_SetElementFocus_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_UnsetElementFocus_simpleEdit(
        IFX_HMODULE         hModule,
        IFX_HELEMENT        hElement);

/* Link functions */

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ExecuteLink_cycleInputMode(
        IFX_HMODULE         hModule);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ExecuteLink_showOSK(
        IFX_HMODULE         hModule);

IFX_RETURN_STATUS IFXM_ifxuisimpleedit_ExecuteLink_hideOSK(
        IFX_HMODULE         hModule);

/* Buffer functions */

#ifdef __cplusplus
}
#endif

#endif /* !def IFX_IFXUISIMPLEEDIT_MODULE_H */

