#
#               Copyright 2007 Mentor Graphics Corporation
#                         All Rights Reserved.
#
# THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS THE
# PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS SUBJECT
# TO LICENSE TERMS.
#

# Set the framework source depending on the platform being used.
OBJS += $(OBJDIR)/framework_linux_$(PLATFORM).o

LIBRARY=$(BUILDDIR)/lib/libInflexionUIFramework.a

default: all

include $(BUILDDIR)/inflexionui/library.mk

