/***************************************************************************
*
*               Copyright 2006 Mentor Graphics Corporation
*                         All Rights Reserved.
*
* THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS
* THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS
* SUBJECT TO LICENSE TERMS.
*
****************************************************************************/
#ifndef NdhsXmlDefsH
#define NdhsXmlDefsH

/*-------------------------------------------------------------------------*//**
	This defines the XML tags used in our XML files.
*/

//
//	Generic Template defines.
//
#define NDHS_TP_XML_SETTINGS					"settings"
#define NDHS_TP_XML_TOKENS						"tokens"
#define NDHS_TP_XML_NODE_MENUS					"nodeMenus"
#define NDHS_TP_XML_ACTIONS						"actions"
#define NDHS_TP_XML_ACTION						"action"
#define NDHS_TP_XML_LAYOUTS						"layouts"
#define NDHS_TP_XML_LAYOUT						"layout"
#define NDHS_TP_XML_ANIMATIONS					"animations"
#define NDHS_TP_XML_ANIMATION					"animation"
#define NDHS_TP_XML_DECORATIONS					"decorations"
#define NDHS_TP_XML_TEMPLATE_TYPE				"templateType"
#define NDHS_TP_XML_LIGHT_MODEL					"lightModel"
#define NDHS_TP_XML_TIMING						"timing"
#define NDHS_TP_XML_FOCUS						"focus"
#define NDHS_TP_XML_VARIABLES					"variables"
#define NDHS_TP_XML_PARAMETERS					"parameters"
#define NDHS_TP_XML_NAME						"name"
#define NDHS_TP_XML_MAKES_TRANSLUCENT			"makesTranslucent"
#define NDHS_TP_XML_TRANSITION					"transition"
#define NDHS_TP_XML_TO_LAYOUT					"toLayout"
#define NDHS_TP_XML_SCROLL						"scroll"
#define NDHS_TP_XML_AMOUNT						"amount"
#define NDHS_TP_XML_STATIC						"static"
#define NDHS_TP_XML_DELAY						"delay"
#define NDHS_TP_XML_DURATION					"duration"
#define NDHS_TP_XML_BACKGROUND_DELAY			"backgroundDelay"
#define NDHS_TP_XML_PRIMARY_LIGHT_DELAY			"primaryLightDelay"
#define NDHS_TP_XML_PRIMARY_LIGHT_DURATION		"primaryLightDuration"
#define NDHS_TP_XML_SLOTS						"slots"
#define NDHS_TP_XML_SLOT						"slot"
#define NDHS_TP_XML_SCREEN						"screen"
#define NDHS_TP_XML_PAGE						"page"
#define NDHS_TP_XML_MENU						"menu"
#define NDHS_TP_XML_FURNITURE					"furniture"
#define NDHS_TP_XML_DETAIL						"detail"
#define NDHS_TP_XML_ELEMENT						"element"
#define NDHS_TP_XML_CLASS						"class"
#define NDHS_TP_XML_OUTER_GROUP					"outerGroup"
#define NDHS_TP_XML_GROUP						"group"
#define NDHS_TP_XML_ITEMS						"items"
#define NDHS_TP_XML_ITEM						"item"
#define NDHS_TP_XML_DEFAULTS					"defaults"
#define NDHS_TP_XML_ACTIVE						"active"
#define NDHS_TP_XML_TO_ACTIVE					"toActive"
#define NDHS_TP_XML_FROM_ACTIVE					"fromActive"
#define NDHS_TP_XML_TO_SLOT						"toSlot"
#define NDHS_TP_XML_FROM_SLOT					"fromSlot"
#define NDHS_TP_XML_ON_SLOT						"onSlot"
#define NDHS_TP_XML_ANY							"any"
#define NDHS_TP_XML_LOOP						"loop"
#define NDHS_TP_XML_CLEANUP_TRIGGER				"cleanupTrigger"
#define NDHS_TP_XML_TRIGGERS					"triggers"
#define NDHS_TP_XML_TRIGGER						"trigger"
#define NDHS_TP_XML_KEY							"key"
#define NDHS_TP_XML_VALUE						"value"
#define NDHS_TP_XML_VALUE_TYPE					"dataType"
#define NDHS_TP_XML_POSITION					"position"
#define NDHS_TP_XML_MAX_VELOCITY				"maxVelocity"
#define NDHS_TP_XML_DRAW_PLANE					"drawPlane"
#define NDHS_TP_XML_X							"x"
#define NDHS_TP_XML_Y							"y"
#define NDHS_TP_XML_Z							"z"
#define NDHS_TP_XML_COLOR						"color"
#define NDHS_TP_XML_COLOR2						"color2"
#define NDHS_TP_XML_PRIMARY						"primary"
#define NDHS_TP_XML_THEME_CURRENT				"themeCurrent"
#define NDHS_TP_XML_INTEGRATED					"integrated"
#define NDHS_TP_XML_ANTI_ALIAS					"antiAlias"
#define NDHS_TP_XML_MOUSEOVER_DELAY				"mouseoverDelay"
//
//	Entry Point defines.
//
#define NDHS_TP_XML_ENTRY_POINT_MAP				"entryPointMap"
#define NDHS_TP_XML_ENTRY_POINT					"entryPoint"
#define NDHS_TP_XML_ENTRY_POINT_ID				"entryPointID"
#define NDHS_TP_XML_DEFAULT_ENTRY_POINT_ID		"defaultEntryPointID"
#define NDHS_TP_XML_NODE_URI					"nodeUri"
#define NDHS_TP_XML_DEFAULT_LINK				"defaultLink"

//
//	Menu defines.
//
#define NDHS_TP_XML_SORT_FIELD					"sortField"
#define NDHS_TP_XML_SORT_TYPE					"sortType"
#define NDHS_TP_XML_SORT_DIRECTION				"sortDirection"
#define NDHS_TP_XML_VAL_CASE_SENSITIVE			"caseSensitive"
#define NDHS_TP_XML_VAL_CASE_INSENSITIVE		"caseInsensitive"
#define NDHS_TP_XML_VAL_DESCENDING				"descending"
#define NDHS_TP_XML_LOAD_ON_DEMAND				"loadOnDemand"

//
// Page Template defines.
//
#define NDHS_TP_XML_DESIGN_SIZE					"designSize"
#define NDHS_TP_XML_CLEANUP_LINK				"cleanupLink"
#define NDHS_TP_XML_VISIBILITY					"visibility"
#define NDHS_TP_XML_PARENTS						"parents"
#define NDHS_TP_XML_PARENT						"parent"
#define NDHS_TP_XML_HIDE_ALL_SHOW_ROOT			"hideallshowroot"
#define NDHS_TP_XML_HIDE_DIRECT_PARENT			"hidedirectparent"
#define NDHS_TP_XML_SHOW_DIRECT_PARENT			"showdirectparent"
#define NDHS_TP_XML_SHOW_WHEN_IN_SUB			"showWhenInSub"

//
// Menu Template defines.
//
#define NDHS_TP_XML_CLASSES						"classes"
#define NDHS_TP_XML_JUMP_BY						"jumpby"
#define NDHS_TP_XML_WRAP						"wrap"
#define NDHS_TP_XML_JUMP_TO						"jumpto"
#define NDHS_TP_XML_DEACTIVATE					"deactivate"
#define NDHS_TP_XML_DATA_SOURCE					"dataSource"
#define NDHS_TP_XML_FULL						"full"
#define NDHS_TP_XML_SPAN						"span"
#define NDHS_TP_XML_REBOUND						"rebound"
#define NDHS_TP_XML_KICK						"kick"
#define NDHS_TP_XML_COUNT						"count"
#define NDHS_TP_XML_FIRST_SELECTABLE			"firstSelectable"
#define NDHS_TP_XML_LAST_SELECTABLE				"lastSelectable"
#define NDHS_TP_XML_FIRST_ACTIVE				"firstActive"
#define NDHS_TP_XML_POPULATE_FROM				"populateFrom"

//
//	Template defines.
//
#define NDHS_TP_XML_DISPLACEMENTS				"displacements"
#define NDHS_TP_XML_DISPLACEMENT				"displacement"
#define NDHS_TP_XML__SCROLLPOS					"_scrollpos"
#define NDHS_TP_XML_MAX							"max"
#define NDHS_TP_XML_MIN							"min"
#define NDHS_TP_XML_MAX_VALUE					"maxValue"
#define NDHS_TP_XML_MIN_VALUE					"minValue"
#define NDHS_TP_XML_USAGE						"usage"
#define NDHS_TP_XML_VERTEX_SHADER				"vertexShader"
#define NDHS_TP_XML_FRAGMENT_SHADER				"fragmentShader"
#define NDHS_TP_XML_ATTRIBUTES					"attributes"
#define NDHS_TP_XML_ATTRIBUTE					"attribute"
#define NDHS_TP_XML_UNIFORMS					"uniforms"
#define NDHS_TP_XML_UNIFORM						"uniform"
#define NDHS_TP_XML_BOUNDING_BOX				"boundingBox"
#define NDHS_TP_XML_DATA_TYPE					"dataType"
#define NDHS_TP_XML_EXPRESSION					"expression"
#define NDHS_TP_XML_DEFAULT_VALUE				"defaultValue"
#define NDHS_TP_XML_MODE						"mode"
#define NDHS_TP_XML_LAYOUT_TIME					"layoutTime"
#define NDHS_TP_XML_SCROLL_TIME					"scrollTime"
#define NDHS_TP_XML_TERMINAL_TIME				"terminalTime"
#define NDHS_TP_XML_LAYOUT_VELOCITY_PROFILE		"layoutVelocityProfile"
#define NDHS_TP_XML_SCROLL_VELOCITY_PROFILE		"scrollVelocityProfile"
#define NDHS_TP_XML_TERMINAL_VELOCITY_PROFILE	"terminalVelocityProfile"
#define NDHS_TP_XML_FOCUS_STOP					"focusStop"
#define NDHS_TP_XML_DEFAULT_FOCUS				"defaultFocus"
#define NDHS_TP_XML_SCROLL_BY					"scrollby"
#define NDHS_TP_XML_VELOCITY_PROFILE			"velocityProfile"
#define NDHS_TP_XML_FIELD						"field"
#define NDHS_TP_XML_TYPE						"type"
#define NDHS_TP_XML_BACK						"back"
#define NDHS_TP_XML_LINK						"link"
#define NDHS_TP_XML_URI							"uri"
#define NDHS_TP_XML_SUSPEND						"suspend"
#define NDHS_TP_XML_SIGNAL						"signal"
#define NDHS_TP_XML_EXIT						"exit"
#define NDHS_TP_XML_SET_FOCUS					"setfocus"
#define NDHS_TP_XML_UNSET_FOCUS					"unsetfocus"
#define NDHS_TP_XML_MOVE_FOCUS					"movefocus"
#define NDHS_TP_XML_STOP						"stop"
#define NDHS_TP_XML_CONDITION					"condition"
#define NDHS_TP_XML_EVENT_HANDLER				"eventHandler"
#define NDHS_TP_XML_ON_TAP						"onTap"
#define NDHS_TP_XML_ON_SIGNAL					"onSignal"
#define NDHS_TP_XML_ON_PRESS					"onPress"
#define NDHS_TP_XML_INHERITS					"inherits"
#define NDHS_TP_XML_CURVES						"curves"
#define NDHS_TP_XML_CURVE						"curve"
#define NDHS_TP_XML_PRIMARY_LIGHT				"primaryLight"
#define NDHS_TP_XML_HIDE						"hide"
#define NDHS_TP_XML_UNLOAD						"unload"
#define NDHS_TP_XML_FONT						"font"
#define NDHS_TP_XML_SENSITIVITY					"sensitivity"
#define NDHS_TP_XML_INVERTED					"inverted"
#define NDHS_TP_XML_THRESHOLD					"threshold"
#define NDHS_TP_XML_DECELERATION				"deceleration"
#define NDHS_TP_XML_FACE						"face"
#define NDHS_TP_XML_STYLE						"style"
#define NDHS_TP_XML_OPENGL_RENDER_QUALITY		"openGLRenderQuality"
#define NDHS_TP_XML_TAP_TOLERANCE				"tapTolerance"
#define NDHS_TP_XML_TAPPABLE					"tappable"
#define NDHS_TP_XML_QUALITY						"quality"
#define NDHS_TP_XML_VISUAL_EFFECT				"visualEffect"
#define NDHS_TP_XML_USE_CUSTOM_EFFECT			"useCustomEffect"
#define NDHS_TP_XML_SHADER_SOURCE				"shaderSource"
#define NDHS_TP_XML_ENGINE_MAPPING				"engineMapping"
#define NDHS_TP_XML_USAGE						"usage"
#define NDHS_TP_XML_MIP_MAP						"mipMap"
#define NDHS_TP_XML_FILE						"file"
#define NDHS_TP_XML_EXCLUDED					"excluded"
#define NDHS_TP_XML_COMPILED_SHADER_FORMAT		"compiledShaderFormat"
#define NDHS_TP_XML_FOCUS_ORDER					"focusOrder"
#define NDHS_TP_XML_ENABLE_FOCUS				"enableFocus"
#define NDHS_TP_XML_HEIGHT						"height"
#define NDHS_TP_XML_HALIGN						"hAlign"
#define NDHS_TP_XML_VALIGN						"vAlign"
#define NDHS_TP_XML_ABBREV_SUFFIX				"abbrevSuffix"
#define NDHS_TP_XML_RESOURCE					"resource"
#define NDHS_TP_XML_VERTICAL_MARQUEE			"verticalMarquee"
#define NDHS_TP_XML_HORIZONTAL_MARQUEE			"horizontalMarquee"
#define NDHS_TP_XML_MARQUEE_SPEED				"marqueeSpeed"
#define NDHS_TP_XML_FORMAT						"format"
#define NDHS_TP_XML_DATA						"data"
#define NDHS_TP_XML_EFFECT_UNIFORMS				"effectUniforms"
#define NDHS_TP_XML_UNIFORM_TYPE				"uniformType"
#define NDHS_TP_XML_UNIFORM_VALUE				"uniformValue"
#define NDHS_TP_XML_TELEPORT					"teleport"
#define NDHS_TP_XML_PATH						"path"
#define NDHS_TP_XML_CLIPPING_AREA				"clippingArea"
#define NDHS_TP_XML_PARAMETER_BINDINGS			"parameterBindings"
#define NDHS_TP_XML_PARAMETER_BINDING			"parameterBinding"
#define NDHS_TP_XML_SPECULAR_COLOR				"specularColor"
#define NDHS_TP_XML_MATERIAL_SPECULAR_COLOR		"materialSpecularColor"
#define NDHS_TP_XML_MATERIAL_EMISSIVE_COLOR		"materialEmissiveColor"
#define NDHS_TP_XML_MATERIAL_SPECULAR_SHININESS	"materialSpecularShininess"
#define NDHS_TP_XML_FRAME_COUNT					"frameCount"
#define NDHS_TP_XML_X_DRAG						"xDrag"
#define NDHS_TP_XML_Y_DRAG						"yDrag"
#define NDHS_TP_XML_ATTENUATION					"attenuation"
#define NDHS_TP_XML_CONSTANT					"constant"
#define NDHS_TP_XML_LINEAR						"linear"
#define NDHS_TP_XML_QUADRATIC					"quadratic"
#define NDHS_TP_XML_UID_CLASS_SETTINGS			"uid-classSettings"
#define NDHS_TP_XML_MESHGRID					"meshGrid"
#define NDHS_TP_XML_MESHGRID_X					"x"
#define NDHS_TP_XML_MESHGRID_Y					"y"

//
//	Page defines.
//
#define NDHS_TP_XML_UI_FLOW_NODES				"uiFlowNodes"
#define NDHS_TP_XML_NODE						"node"

//
//	Key Value List defines.
//
#define NDHS_TP_XML_ID							"id"

//
//	Placement defines.
//
#define NDHS_TP_XML_SCALE						"scale"
#define NDHS_TP_XML_OFFSET						"offset"
#define NDHS_TP_XML_INTENSITY					"intensity"
#define NDHS_TP_XML_ORIENTATION					"orientation"
#define NDHS_TP_XML_AZIMUTH						"azimuth"
#define NDHS_TP_XML_ELEVATION					"elevation"
#define NDHS_TP_XML_ROLL						"roll"
#define NDHS_TP_XML_ROTATION					"rotation"
#define NDHS_TP_XML_ANGLE						"angle"
#define NDHS_TP_XML_LOCATION					"location"
#define NDHS_TP_XML_EXTENT						"extent"
#define NDHS_TP_XML_EXTENT_HINT					"extentHint"
#define NDHS_TP_XML_FRAME						"frame"
#define NDHS_TP_XML_OPACITY						"opacity"

//
//	Package defines.
//
#define NDHS_TP_XML_MENU_INSERT					"insert"
#define NDHS_TP_XML_PALETTES					"palettes"
#define NDHS_TP_XML_PALETTE						"palette"
#define NDHS_TP_XML_DEFAULT_THEME				"defaultTheme"
#define NDHS_TP_XML_GUID						"GUID"
#define NDHS_TP_XML_DISPLAYS					"displays"
#define NDHS_TP_XML_DISPLAY						"display"
#define NDHS_TP_XML_WIDTH						"width"
#define NDHS_TP_XML_HEIGHT						"height"
#define NDHS_TP_XML_ORIGIN						"origin"
#define NDHS_TP_XML_DESIGN_SIZES				"designSizes"
#define NDHS_TP_XML_KEYS						"keys"
#define NDHS_TP_XML_SCAN_CODE					"scanCode"
#define NDHS_TP_XML_SIMTEST_CODE				"simtestCode"

#endif	// NdhsXmlDefsH
