CFLAGS+=-I.

OBJS = \
$(OBJDIR)/hb-blob.o \
$(OBJDIR)/hb-buffer.o \
$(OBJDIR)/hb-common.o \
$(OBJDIR)/hb-fallback-shape.o \
$(OBJDIR)/hb-font.o \
$(OBJDIR)/hb-ft.o \
$(OBJDIR)/hb-ot-layout.o \
$(OBJDIR)/hb-ot-map.o \
$(OBJDIR)/hb-ot-shape.o \
$(OBJDIR)/hb-ot-shape-complex-arabic.o \
$(OBJDIR)/hb-ot-shape-complex-indic.o \
$(OBJDIR)/hb-ot-shape-complex-misc.o \
$(OBJDIR)/hb-ot-shape-normalize.o \
$(OBJDIR)/hb-ot-tag.o \
$(OBJDIR)/hb-set.o \
$(OBJDIR)/hb-shape.o \
$(OBJDIR)/hb-tt-font.o \
$(OBJDIR)/hb-unicode.o

LIBRARY = $(BUILDDIR)/lib/libHarfbuzz.a
default: all
include $(BUILDDIR)/inflexionui/library.mk

