/* File auto-generated by Mentor Graphics Tools */

struct LcTRomFileEntry
{
	const char*						name;
	unsigned						length;
	const unsigned char*			data;
};

#include "DefaultShaders-1.0.0_FileData.dat"

const unsigned g_shaderRomFileCount = 48;

const struct LcTRomFileEntry g_shaderRomFileTable[] =
{
	{ "settings.xml", 431, g_shader_settings_2Exml },
	{ "High/high_texlight_0.vert", 4309, g_shader_high_2Fhigh__texlight__0_2Evert },
	{ "High/high_alphalight_0.frag", 3877, g_shader_high_2Fhigh__alphalight__0_2Efrag },
	{ "Effects/high_alphalight_0.effect", 4106, g_shader_effects_2Fhigh__alphalight__0_2Eeffect },
	{ "High/high_texlight_1.vert", 1917, g_shader_high_2Fhigh__texlight__1_2Evert },
	{ "High/high_alphalight_1.frag", 1463, g_shader_high_2Fhigh__alphalight__1_2Efrag },
	{ "Effects/high_alphalight_1.effect", 2378, g_shader_effects_2Fhigh__alphalight__1_2Eeffect },
	{ "High/high_texlight_2.vert", 2694, g_shader_high_2Fhigh__texlight__2_2Evert },
	{ "High/high_alphalight_2.frag", 2684, g_shader_high_2Fhigh__alphalight__2_2Efrag },
	{ "Effects/high_alphalight_2.effect", 3321, g_shader_effects_2Fhigh__alphalight__2_2Eeffect },
	{ "High/high_light_0.vert", 4139, g_shader_high_2Fhigh__light__0_2Evert },
	{ "High/high_light_0.frag", 3715, g_shader_high_2Fhigh__light__0_2Efrag },
	{ "Effects/high_light_0.effect", 3835, g_shader_effects_2Fhigh__light__0_2Eeffect },
	{ "High/high_light_1.vert", 1629, g_shader_high_2Fhigh__light__1_2Evert },
	{ "High/high_light_1.frag", 1301, g_shader_high_2Fhigh__light__1_2Efrag },
	{ "Effects/high_light_1.effect", 2107, g_shader_effects_2Fhigh__light__1_2Eeffect },
	{ "High/high_light_2.vert", 2524, g_shader_high_2Fhigh__light__2_2Evert },
	{ "High/high_light_2.frag", 2516, g_shader_high_2Fhigh__light__2_2Efrag },
	{ "Effects/high_light_2.effect", 3050, g_shader_effects_2Fhigh__light__2_2Eeffect },
	{ "High/high_texlight_0.frag", 3847, g_shader_high_2Fhigh__texlight__0_2Efrag },
	{ "Effects/high_texlight_0.effect", 4096, g_shader_effects_2Fhigh__texlight__0_2Eeffect },
	{ "High/high_texlight_1.frag", 1432, g_shader_high_2Fhigh__texlight__1_2Efrag },
	{ "Effects/high_texlight_1.effect", 2368, g_shader_effects_2Fhigh__texlight__1_2Eeffect },
	{ "High/high_texlight_2.frag", 2650, g_shader_high_2Fhigh__texlight__2_2Efrag },
	{ "Effects/high_texlight_2.effect", 3351, g_shader_effects_2Fhigh__texlight__2_2Eeffect },
	{ "Normal/normal_texlight_0.vert", 5835, g_shader_normal_2Fnormal__texlight__0_2Evert },
	{ "Normal/normal_alphalight.frag", 427, g_shader_normal_2Fnormal__alphalight_2Efrag },
	{ "Effects/normal_alphalight_0.effect", 4104, g_shader_effects_2Fnormal__alphalight__0_2Eeffect },
	{ "Normal/normal_texlight_1.vert", 2162, g_shader_normal_2Fnormal__texlight__1_2Evert },
	{ "Effects/normal_alphalight_1.effect", 2376, g_shader_effects_2Fnormal__alphalight__1_2Eeffect },
	{ "Normal/normal_texlight_2.vert", 3808, g_shader_normal_2Fnormal__texlight__2_2Evert },
	{ "Effects/normal_alphalight_2.effect", 3319, g_shader_effects_2Fnormal__alphalight__2_2Eeffect },
	{ "Normal/normal_background.vert", 608, g_shader_normal_2Fnormal__background_2Evert },
	{ "Normal/normal_background.frag", 301, g_shader_normal_2Fnormal__background_2Efrag },
	{ "Effects/normal_background.effect", 1200, g_shader_effects_2Fnormal__background_2Eeffect },
	{ "Normal/normal_light_0.vert", 5666, g_shader_normal_2Fnormal__light__0_2Evert },
	{ "Normal/normal_light.frag", 235, g_shader_normal_2Fnormal__light_2Efrag },
	{ "Effects/normal_light_0.effect", 3833, g_shader_effects_2Fnormal__light__0_2Eeffect },
	{ "Normal/normal_light_1.vert", 1993, g_shader_normal_2Fnormal__light__1_2Evert },
	{ "Effects/normal_light_1.effect", 2105, g_shader_effects_2Fnormal__light__1_2Eeffect },
	{ "Normal/normal_light_2.vert", 3644, g_shader_normal_2Fnormal__light__2_2Evert },
	{ "Effects/normal_light_2.effect", 3048, g_shader_effects_2Fnormal__light__2_2Eeffect },
	{ "Normal/normal_texlight.frag", 348, g_shader_normal_2Fnormal__texlight_2Efrag },
	{ "Effects/normal_texlight_0.effect", 4094, g_shader_effects_2Fnormal__texlight__0_2Eeffect },
	{ "Effects/normal_texlight_1.effect", 2366, g_shader_effects_2Fnormal__texlight__1_2Eeffect },
	{ "Effects/normal_texlight_2.effect", 3309, g_shader_effects_2Fnormal__texlight__2_2Eeffect },
	{ "manifest.xml", 2679, g_shader_manifest_2Exml },
	{ "manifest.sig", 20, g_shader_manifest_2Esig }
};
